### ISSUE TITLE
RuntimeError: NLPIR function 'NLPIR_Init' failed.

### ISSUE THREAD

**Issue by saliay** [tsroten/pynlpir#104]
[我在运行程序时总是出现这个东西，我看了之前的问题，也尝试着改了文件权限，但是还是一样的结果，不知该怎么办了

下面是我运行的结果
D:\爬虫\python\Python36\python.exe D:/srtp/分词系统/pynlpir-develop/one.py
Traceback (most recent call last):
  File "D:/srtp/分词系统/pynlpir-develop/one.py", line 21, in <module>
    pynlpir.open()
  File "D:\srtp\分词系统\pynlpir-develop\pynlpir\__init__.py", line 108, in open
    raise RuntimeError("NLPIR function 'NLPIR_Init' failed.")
RuntimeError: NLPIR function 'NLPIR_Init' failed.
[2018-01-26 10:37:03] Failed open file  D:\srtp\分词系统\pynlpir-develop\pynlpir\Data\Configure.xml
Cannot write log file D:\srtp\分词系统\pynlpir-develop\pynlpir\Data\20180126.log!
[2018-01-26 10:37:03] Cannot Open Configure file D:\srtp\分词系统\pynlpir-develop\pynlpir\Data\Configure.xml
Cannot write log file D:\srtp\分词系统\pynlpir-develop\pynlpir\Data\20180126.err!

Process finished with exit code 1

**Comment by yuanlily** [comment]
试试命令行前加上sudo?
