### ISSUE TITLE
I find a bug when I install pynlpir by pip-install on Mac OS X

### ISSUE THREAD

**Issue by lucosax** [tsroten/pynlpir#12]
Downloading/unpacking pynlpir
  Downloading PyNLPIR-0.1.3.tar.gz (12.7MB): 12.7MB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/pynlpir/setup.py) egg_info for package pynlpir
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/tmp/pip_build_root/pynlpir/setup.py", line 12, in <module>
        import pynlpir
      File "pynlpir/**init**.py", line 24, in <module>
        from . import nlpir, pos_map
      File "pynlpir/nlpir.py", line 120, in <module>
        libNLPIR = load_library(sys.platform, is_64bit)
      File "pynlpir/nlpir.py", line 111, in load_library
        platform)
    RuntimeError: Platform 'darwin' is not supported by NLPIR.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/tmp/pip_build_root/pynlpir/setup.py", line 12, in <module>

```
import pynlpir
```

  File "pynlpir/**init**.py", line 24, in <module>

```
from . import nlpir, pos_map
```

  File "pynlpir/nlpir.py", line 120, in <module>

```
libNLPIR = load_library(sys.platform, is_64bit)
```

  File "pynlpir/nlpir.py", line 111, in load_library

```
platform)
```

RuntimeError: Platform 'darwin' is not supported by NLPIR.

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/pynlpir
Storing debug log for failure in /Users/Lucosax/Library/Logs/pip.log

thanks

**Comment by JetMuffin** [comment]
so sad to hear that, i meet the same problem

**Comment by tsroten** [comment]
If you would like OS X support, please let NLPIR/ICTCLAS know: http://ictclas.nlpir.org

**Comment by tsroten** [comment]
@lucosax @JetMuffin Good news! PyNLPIR now supports OS X. The GitHub repository has the latest code. I'm going to release to PyPI later today.
