### ISSUE TITLE
ValueError: part of speech not recognized: 'grjyy'

### ISSUE THREAD

**Issue by risent** [tsroten/pynlpir#24]
```
s = u"很多阅读材料，两个quiz，一个问卷调查还有一个office hour，"
pynlpir.segment(s)

```

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/risent/Code/ylan/moocenv/lib/python2.7/site-packages/pynlpir/__init__.py", line 184, in segment
    pos_name = _get_pos_name(token[1], pos_names, pos_english)
  File "/home/risent/Code/ylan/moocenv/lib/python2.7/site-packages/pynlpir/__init__.py", line 129, in _get_pos_name
    pos_name = pos_map.get_pos_name(code, name, english)
  File "/home/risent/Code/ylan/moocenv/lib/python2.7/site-packages/pynlpir/pos_map.py", line 184, in get_pos_name
    return _get_pos_name(code, name, english)
  File "/home/risent/Code/ylan/moocenv/lib/python2.7/site-packages/pynlpir/pos_map.py", line 150, in _get_pos_name
    pos_code)
ValueError: part of speech not recognized: 'grjyy'
```

**Comment by tsroten** [comment]
Thank you for reporting this. #20 addresses this already. A fix has been committed, but hasn't been published on PyPI yet. Stay tuned for a new release soon.

**Comment by tsroten** [comment]
Okay, sorry for the delay, but it's now included in the most recent release of PyNLPIR.

**Comment by risent** [comment]
:smile: thanks!
