### ISSUE TITLE
RuntimeError: NLPIR function 'NLPIR_Init' failed.

### ISSUE THREAD

**Issue by jingjinjingjin** [tsroten/pynlpir#25]
$ git clone https://github.com/tsroten/pynlpir.git
$ sudo pip install -e pynlpir
Obtaining file:///home/jingjin/pynlpir
Installing collected packages: PyNLPIR
  Running setup.py develop for PyNLPIR
Successfully installed PyNLPIR

$ python setup.py test
running test
running egg_info
writing PyNLPIR.egg-info/PKG-INFO
writing top-level names to PyNLPIR.egg-info/top_level.txt
writing dependency_links to PyNLPIR.egg-info/dependency_links.txt
reading manifest file 'PyNLPIR.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
writing manifest file 'PyNLPIR.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    test_suite='pynlpir.tests'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 135, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 116, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 160, in run_tests
    testLoader = cks
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/jingjin/pynlpir/pynlpir/tests/test_init.py", line 8, in <module>
    pynlpir.open()
  File "/home/jingjin/pynlpir/pynlpir/__init__.py", line 80, in open
    raise RuntimeError("NLPIR function 'NLPIR_Init' failed.")
RuntimeError: NLPIR function 'NLPIR_Init' failed.

**Comment by jingjinjingjin** [comment]
Resolved!
download http://ictclas.nlpir.org/upload/20150702124141_ICTCLAS2015.zip
replace Data directory

**Comment by tsroten** [comment]
@jingjinjingjin Thanks for reporting this! It's difficult to keep track of when new NLPIR releases come out. I've updated the Data directory (bf9cef12203cb632423f63cef86fa185c2dbe5a3).

**Comment by tsroten** [comment]
Alright, this is now included in the most recent release of PyNLPIR.
