### ISSUE TITLE
Not valid license or your license expired!

### ISSUE THREAD

**Issue by taozhijiang** [tsroten/pynlpir#31]
Hi, tsroten, another question may bother you ;-)

```python
➜  correct_me ./wds.py 
Traceback (most recent call last):
  File "./wds.py", line 201, in <module>
    pynlpir.open()
  File "/store/user_homes/Study/MachLearn/sogou_txt/correct_me/pynlpir/pynlpir/__init__.py", line 97, in open
    raise RuntimeError("NLPIR function 'NLPIR_Init' failed.")
RuntimeError: NLPIR function 'NLPIR_Init' failed.
➜  correct_me cat pynlpir/pynlpir/Data/20150801.err 
[2015-08-01 00:23:31]   /store/user_homes/Study/MachLearn/sogou_txt/correct_me/pynlpir/pynlpir/Data/NLPIR.user Not valid license or your license expired! Please feel free to contact pipy_zhang@msn.com! 
[2015-08-01 00:35:22]   /store/user_homes/Study/MachLearn/sogou_txt/correct_me/pynlpir/pynlpir/Data/NLPIR.user Not valid license or your license expired! Please feel free to contact pipy_zhang@msn.com! 
[2015-08-01 00:37:36]   /store/user_homes/Study/MachLearn/sogou_txt/correct_me/pynlpir/pynlpir/Data/NLPIR.user Not valid license or your license expired! Please feel free to contact pipy_zhang@msn.com! 
➜  correct_me 
```

**Comment by tsroten** [comment]
Can you double check what version of PyNLPIR you have? Try this:
```python
import pynlpir
print(pynlpir.__version__)
```

Make sure it's version `0.3.1`. If not, you'll need to update to the latest version.

**Comment by taozhijiang** [comment]
Yesterday, all works fine, but when the date time turn, it suddenly appear this problem. I guest the code may have something related to time issue.

Whether from pip repo or the github latest develop branch, this problem happens 100%

➜  correct_me python
Python 3.4.1 (default, Apr 25 2015, 16:07:13) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pynlpir
>>> pynlpir.open()
[2015-08-01 07:02:49] /usr/lib64/python3.4/site-packages/pynlpir/Data/NLPIR.user Not valid license or your license expired! Please feel free to contact pipy_zhang@msn.com! 
Cannot write log file /usr/lib64/python3.4/site-packages/pynlpir/Data/20150801.err!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/pynlpir/__init__.py", line 97, in open
    raise RuntimeError("NLPIR function 'NLPIR_Init' failed.")
RuntimeError: NLPIR function 'NLPIR_Init' failed.
>>> print(pynlpir.__version__)
0.3.1
>>>

**Comment by taozhijiang** [comment]
It is strange. I changed my another workstation machine's time to old, then it works there:

 vmuser@localhost  ~  python3
Python 3.4.2 (default, Jan 12 2015, 12:13:20) 
[GCC 4.9.2 20150107 (Red Hat 4.9.2-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pynlpir
>>> pynlpir.open()
[2015-08-01 07:12:40] /usr/lib/python3.4/site-packages/pynlpir/Data/NLPIR.user Not valid license or your license expired! Please feel free to contact pipy_zhang@msn.com! 
Cannot write log file /usr/lib/python3.4/site-packages/pynlpir/Data/20150801.err!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/pynlpir/__init__.py", line 97, in open
    raise RuntimeError("NLPIR function 'NLPIR_Init' failed.")
RuntimeError: NLPIR function 'NLPIR_Init' failed.
>>> quit()
 vmuser@localhost  ~  date
2015年 08月 01日 星期六 07:12:44 CST


 ✘ vmuser@localhost  ~  sudo date -s "20150720"
2015年 07月 20日 星期一 00:00:00 CST

 vmuser@localhost  ~  /usr/bin/python3
Python 3.4.2 (default, Jan 12 2015, 12:13:20) 
[GCC 4.9.2 20150107 (Red Hat 4.9.2-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pynlpir
>>> pynlpir.open()
[2015-07-20 00:00:59] Cannot open file /usr/lib/python3.4/site-packages/pynlpir/Data/NewWord.lst
Cannot write log file /usr/lib/python3.4/site-packages/pynlpir/Data/20150720.err!
>>> quit()
 vmuser@localhost  ~ 

**Comment by tsroten** [comment]
@taozhijiang It looks like NLPIR's license doesn't work after August 1. We'll have to wait for an official update from NLPIR/ICTCLAS. Changing your system's date is one workaround (as you've already figured out).

**Comment by taozhijiang** [comment]
Have you tested under your own environment?
And will you update it when upstream accessible, and we just need to pull your latest update ?

**Comment by tsroten** [comment]
I did test it and had the same problem. Unfortunately we can't fix this issue until NLPIR releases a new user license. The good news is that it looks like [they just did](http://ictclas.nlpir.org/newsdownloads?DocId=389)! It was released on August 5. I'll publish a new release later today.

**Comment by tsroten** [comment]
@taozhijiang It should be working now. Download [the latest version from PyPI](https://pypi.python.org/pypi/PyNLPIR) and give it a try.
