### ISSUE TITLE
Can PyNLPIR run on Python 3.2?

### ISSUE THREAD

**Issue by cidrugHug8** [tsroten/pynlpir#77]
I tried to update pynlpir and failed.  The error is described below:

> Traceback (most recent call last):
  File "/usr/local/bin/pynlpir", line 9, in <module>
    load_entry_point('PyNLPIR==0.5.2', 'console_scripts', 'pynlpir')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2280, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1990, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.2/dist-packages/PyNLPIR-0.5.2-py3.2.egg/pynlpir/cli.py", line 14, in <module>
    import click
  File "/usr/local/lib/python3.2/dist-packages/click-6.7-py3.2.egg/click/__init__.py", line 18, in <module>
    from .core import Context, BaseCommand, Command, MultiCommand, Group, \
  File "/usr/local/lib/python3.2/dist-packages/click-6.7-py3.2.egg/click/core.py", line 8, in <module>
    from .types import convert_type, IntRange, BOOL
  File "/usr/local/lib/python3.2/dist-packages/click-6.7-py3.2.egg/click/types.py", line 6, in <module>
    from .exceptions import BadParameter
  File "/usr/local/lib/python3.2/dist-packages/click-6.7-py3.2.egg/click/exceptions.py", line 2, in <module>
    from .utils import echo
  File "/usr/local/lib/python3.2/dist-packages/click-6.7-py3.2.egg/click/utils.py", line 224
    message = message or u''
                           ^
SyntaxError: invalid syntax

Could you give me some advice?

**Comment by tsroten** [comment]
Hello @cidrugHug8 Thanks for using PyNLPIR.

It looks like you are running Python 3.2. PyNLPIR does not support version 3.2 because it is officially considered "end-of-life" -- it doesn't get any support or updates.

PyNLPIR supports Python 2.7, 3.3, 3.4, 3.5, or 3.6.

Here is the document on the current status of Python versions: https://docs.python.org/devguide/#status-of-python-branches

**Comment by cidrugHug8** [comment]
Thank you for the reply. 
I updated Ubuntu to 14.0.4
Thanks.
